/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.josephmate.google.kickstart

import kotlin.test.Test
import kotlin.test.assertNotNull

class Problem1NumberGuessingTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Guess();
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
